<?php

namespace ZEN\MessageBundle\Repository;

use ZEN\MessageBundle\Repository\TranslatableRepository;
    
/**
 * CatMessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CatMessageRepository extends TranslatableRepository {

    public function getCatMessageByLangue($langue) {

        $qb = $this->createQueryBuilder('ct')
               /* ->leftJoin('ct.catMessageLang', 'ctl')
                ->addSelect('ctl')
                ->where('ctl.language = ' . $langue)*/;

        return $qb;
    }

}
